basePath: /api/v1
definitions:
  models.CategoriaDTO:
    properties:
      nome:
        type: string
    type: object
  models.ErrorExample:
    properties:
      error:
        type: string
    type: object
  models.ResponseExample:
    properties:
      data: {}
      message:
        type: string
    type: object
  models.TodoDTO:
    properties:
      categoria_id:
        type: integer
      completed:
        type: boolean
      description:
        type: string
      title:
        type: string
    type: object
  models.TodoUpdateDTO:
    properties:
      categoria_id:
        type: integer
      description:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: joaquimjambo12@gmail.com
    name: Joaquim Jambo
    url: https://www.linkedin.com/in/joaquimjambo
  description: API para gerenciar tarefas e listas de tarefas.
  license:
    name: Joaquim Jambo
    url: https://www.linkedin.com/in/joaquimjambo
  termsOfService: http://swagger.io/terms/
  title: DoneGoAPI
  version: "1.0"
paths:
  /category:
    get:
      description: Retorna todas as categorias da base de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ResponseExample'
            type: array
        "500":
          description: Falha ao listar as categorias
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Lista todas as categorias
      tags:
      - Categorias
    post:
      consumes:
      - application/json
      description: Adiciona uma nova categoria à base de dados
      parameters:
      - description: Dados da categoria
        in: body
        name: categoria
        required: true
        schema:
          $ref: '#/definitions/models.CategoriaDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Falha ao adicionar Categoria
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Cria uma nova categoria
      tags:
      - Categorias
  /category/{id}:
    delete:
      description: Exclui uma categoria com base no ID
      parameters:
      - description: ID da categoria
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Categoria deletada com sucesso
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: ID inválido ou mal formado
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Categoria não encontrada
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Remove uma categoria
      tags:
      - Categorias
    get:
      description: Retorna os detalhes de uma categoria específica com base no seu
        ID
      parameters:
      - description: ID da categoria a ser buscada
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Categoria não encontrada!
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Busca uma categoria por ID
      tags:
      - Categorias
    put:
      consumes:
      - application/json
      description: Atualiza os detalhes de uma categoria com base no ID fornecido
      parameters:
      - description: ID da categoria a ser atualizada
        in: path
        name: id
        required: true
        type: integer
      - description: Dados da categoria para atualização
        in: body
        name: categoria
        required: true
        schema:
          $ref: '#/definitions/models.CategoriaDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Categoria não encontrada ou falha ao atualizar
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Atualiza uma categoria existente
      tags:
      - Categorias
  /todo:
    get:
      description: Retorna todas as tarefas da base de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ResponseExample'
            type: array
        "500":
          description: Falha ao listar as tarefas
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Lista todas as tarefas
      tags:
      - Tarefas
    post:
      consumes:
      - application/json
      description: Adiciona uma nova tarefa à base de dados
      parameters:
      - description: Dados da tarefa
        in: body
        name: tarefa
        required: true
        schema:
          $ref: '#/definitions/models.TodoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Falha ao adicionar tarefa
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Cria uma nova tarefa
      tags:
      - Tarefas
  /todo/{id}:
    delete:
      description: Exclui uma tarefa com base no ID
      parameters:
      - description: ID da tarefa
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Tarefa deletada com sucesso
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: ID inválido ou mal formado
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Tarefa não encontrada
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Remove uma tarefa
      tags:
      - Tarefas
    get:
      description: Retorna os detalhes de uma tarefa específica com base no seu ID
      parameters:
      - description: ID da tarefa a ser buscada
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Tarefa não encontrada!
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Busca uma tarefa por ID
      tags:
      - Tarefas
    put:
      consumes:
      - application/json
      description: Atualiza os detalhes de uma tarefa com base no ID fornecido
      parameters:
      - description: ID da tarefa a ser atualizada
        in: path
        name: id
        required: true
        type: integer
      - description: Dados da tarefa para atualização
        in: body
        name: tarefa
        required: true
        schema:
          $ref: '#/definitions/models.TodoUpdateDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Tarefa não encontrada ou falha ao atualizar
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Atualiza uma tarefa existente
      tags:
      - Tarefas
  /todo/{id}/completed:
    patch:
      description: Atualiza o status de uma tarefa para concluída com base no ID
      parameters:
      - description: ID da tarefa
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseExample'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/models.ErrorExample'
        "404":
          description: Tarefa não encontrada
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Marca uma tarefa como concluída
      tags:
      - Tarefas
  /todo/completed:
    get:
      description: Retorna todas as tarefas que foram marcadas como completas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ResponseExample'
            type: array
        "500":
          description: Erro ao buscar tarefas completadas
          schema:
            $ref: '#/definitions/models.ErrorExample'
      summary: Lista tarefas completadas
      tags:
      - Tarefas
swagger: "2.0"
